<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlamingIRC\FlamingIRC.csproj" />
    <ProjectReference Include="..\MutinyIRC.Common\MutinyIRC.Common.csproj" />
    <ProjectReference Include="..\MutinyIRC.PluginFramework\MutinyIRC.PluginFramework.csproj" />
  </ItemGroup>

</Project>
