<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OrtzIRC.Commands</RootNamespace>
    <AssemblyName>OrtzIRC.Commands</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlamingIRC\FlamingIRC.csproj" />
    <ProjectReference Include="..\OrtzIRC.Common\OrtzIRC.Common.csproj" />
    <ProjectReference Include="..\OrtzIRC.PluginFramework\OrtzIRC.PluginFramework.csproj" />
  </ItemGroup>

  <Target Name="CopyPluginToWPF" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)..\OrtzIRC.WPF\bin\$(Configuration)\net8.0-windows\plugins\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).xml" DestinationFolder="$(MSBuildThisFileDirectory)..\OrtzIRC.WPF\bin\$(Configuration)\net8.0-windows\plugins\" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)$(AssemblyName).xml')" />
  </Target>

  <Target Name="CopyPluginToAvalonia" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildThisFileDirectory)..\OrtzIRC.Avalonia\bin\$(Configuration)\net8.0\plugins\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).xml" DestinationFolder="$(MSBuildThisFileDirectory)..\OrtzIRC.Avalonia\bin\$(Configuration)\net8.0\plugins\" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)$(AssemblyName).xml')" />
  </Target>

</Project>
