//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrtzIRC.HostSideAdapters
{
    
    public class ICommandHostAdapter
    {
        internal static OrtzIRC.ICommand ContractToViewAdapter(OrtzIRC.Contracts.ICommandContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ICommandViewToContractHostAdapter))))
            {
                return ((ICommandViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ICommandContractToViewHostAdapter(contract);
            }
        }
        internal static OrtzIRC.Contracts.ICommandContract ViewToContractAdapter(OrtzIRC.ICommand view)
        {
            if (view.GetType().Equals(typeof(ICommandContractToViewHostAdapter)))
            {
                return ((ICommandContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ICommandViewToContractHostAdapter(view);
            }
        }
    }
}

