<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OrtzIRC.Common</RootNamespace>
    <AssemblyName>OrtzIRC.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlamingIRC\FlamingIRC.csproj" />
  </ItemGroup>

</Project>
