//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("serversModel", "FK_Servers_0", "Networks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OrtzIRC.Common.Networks), "Servers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OrtzIRC.Common.Servers))]

// Original file name:
// Generation date: 5/11/2009 11:48:24 PM
namespace OrtzIRC.Common
{
    
    /// <summary>
    /// There are no comments for serversEntities in the schema.
    /// </summary>
    public partial class serversEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new serversEntities object using the connection string found in the 'serversEntities' section of the application configuration file.
        /// </summary>
        public serversEntities() : 
                base("name=serversEntities", "serversEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new serversEntities object.
        /// </summary>
        public serversEntities(string connectionString) : 
                base(connectionString, "serversEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new serversEntities object.
        /// </summary>
        public serversEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "serversEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Networks in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Networks> Networks
        {
            get
            {
                if ((this._Networks == null))
                {
                    this._Networks = base.CreateQuery<Networks>("[Networks]");
                }
                return this._Networks;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Networks> _Networks;
        /// <summary>
        /// There are no comments for Servers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Servers> Servers
        {
            get
            {
                if ((this._Servers == null))
                {
                    this._Servers = base.CreateQuery<Servers>("[Servers]");
                }
                return this._Servers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Servers> _Servers;
        /// <summary>
        /// There are no comments for Networks in the schema.
        /// </summary>
        public void AddToNetworks(Networks networks)
        {
            base.AddObject("Networks", networks);
        }
        /// <summary>
        /// There are no comments for Servers in the schema.
        /// </summary>
        public void AddToServers(Servers servers)
        {
            base.AddObject("Servers", servers);
        }
    }
    /// <summary>
    /// There are no comments for serversModel.Networks in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="serversModel", Name="Networks")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Networks : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Networks object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Networks CreateNetworks(long id, string name)
        {
            Networks networks = new Networks();
            networks.Id = id;
            networks.Name = name;
            return networks;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Servers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("serversModel", "FK_Servers_0", "Servers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Servers> Servers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Servers>("serversModel.FK_Servers_0", "Servers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Servers>("serversModel.FK_Servers_0", "Servers", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for serversModel.Servers in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="serversModel", Name="Servers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Servers : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Servers object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="uri">Initial value of Uri.</param>
        public static Servers CreateServers(long id, string uri)
        {
            Servers servers = new Servers();
            servers.Id = id;
            servers.Uri = uri;
            return servers;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Uri in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri
        {
            get
            {
                return this._Uri;
            }
            set
            {
                this.OnUriChanging(value);
                this.ReportPropertyChanging("Uri");
                this._Uri = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Uri");
                this.OnUriChanged();
            }
        }
        private string _Uri;
        partial void OnUriChanging(string value);
        partial void OnUriChanged();
        /// <summary>
        /// There are no comments for Property Ports in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Ports
        {
            get
            {
                return this._Ports;
            }
            set
            {
                this.OnPortsChanging(value);
                this.ReportPropertyChanging("Ports");
                this._Ports = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Ports");
                this.OnPortsChanged();
            }
        }
        private string _Ports;
        partial void OnPortsChanging(string value);
        partial void OnPortsChanged();
        /// <summary>
        /// There are no comments for Networks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("serversModel", "FK_Servers_0", "Networks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Networks Networks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Networks>("serversModel.FK_Servers_0", "Networks").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Networks>("serversModel.FK_Servers_0", "Networks").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Networks in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Networks> NetworksReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Networks>("serversModel.FK_Servers_0", "Networks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Networks>("serversModel.FK_Servers_0", "Networks", value);
                }
            }
        }
    }
}
