//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrtzIRC.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class ICommandViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, OrtzIRC.Contracts.ICommandContract
    {
        private OrtzIRC.ICommand _view;
        public ICommandViewToContractAddInAdapter(OrtzIRC.ICommand view)
        {
            _view = view;
        }
        public virtual bool Excecute(System.AddIn.Contract.IListContract<string> parameters)
        {
            return _view.Excecute(System.AddIn.Pipeline.CollectionAdapters.ToIList<string>(parameters));
        }
        internal OrtzIRC.ICommand GetSourceView()
        {
            return _view;
        }
    }
}

