//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrtzIRC.AddInSideAdapters
{
    
    public class ICommandContractToViewAddInAdapter : OrtzIRC.ICommand
    {
        private OrtzIRC.Contracts.ICommandContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static ICommandContractToViewAddInAdapter()
        {
        }
        public ICommandContractToViewAddInAdapter(OrtzIRC.Contracts.ICommandContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public bool Excecute(System.Collections.Generic.IList<string> parameters)
        {
            return _contract.Excecute(System.AddIn.Pipeline.CollectionAdapters.ToIListContract<string>(parameters));
        }
        internal OrtzIRC.Contracts.ICommandContract GetSourceContract()
        {
            return _contract;
        }
    }
}

