//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrtzIRC.AddInSideAdapters
{
    
    public class ICommandAddInAdapter
    {
        internal static OrtzIRC.ICommand ContractToViewAdapter(OrtzIRC.Contracts.ICommandContract contract)
        {
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ICommandViewToContractAddInAdapter))))
            {
                return ((ICommandViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ICommandContractToViewAddInAdapter(contract);
            }
        }
        internal static OrtzIRC.Contracts.ICommandContract ViewToContractAdapter(OrtzIRC.ICommand view)
        {
            if (view.GetType().Equals(typeof(ICommandContractToViewAddInAdapter)))
            {
                return ((ICommandContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ICommandViewToContractAddInAdapter(view);
            }
        }
    }
}

